version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./logs:/var/log/apache2
      - ./config/app.env:/var/www/html/.env
      - ./config/app.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network

  landing:
    image: php:7.4-apache
    container_name: landing
    volumes:
      - ./landing:/var/www/html
      - ./logs:/var/log/apache2
      - ./config/landing.env:/var/www/html/.env
      - ./config/landing.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mariadb
    container_name: db
    volumes:
      - ./data:/var/lib/mysql
      - ./config/db.env:/etc/mysql/conf.d/app.cnf
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    networks:
      - app_network

networks:
  app_network:

volumes:
  data:
  logs:
  config:
