FROM php:8.1-apache

COPY ./apache.landing.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite

WORKDIR /var/www/html

# Set ownership to www-data user and group
RUN chown -R www-data:www-data /var/www/html

# Set file permissions to 755
RUN chmod -R 755 /var/www/html

CMD ["apache2-foreground"]
